name: Android Build & Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual triggering

jobs:
  # Main Android app build (Curtain app)
  build-curtain-app:
    name: Build Curtain Android App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install build tools
        run: |
          ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "build-tools;35.0.0"
          ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "platforms;android-35"

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Download required assets
        run: ./gradlew downloadPlotly downloadQRCodeStyling

      - name: Build Curtain App Release APK and Bundle
        run: ./gradlew :app:assembleRelease :app:bundleRelease

      - name: Sign Curtain App APK
        uses: r0adkll/sign-android-release@v1
        id: sign_apk
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: curtain-key
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "35.0.0"

      - name: Sign Curtain App Bundle
        uses: r0adkll/sign-android-release@v1
        id: sign_bundle
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: curtain-key
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "35.0.0"
          
      - name: Set version from tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            VERSION="dev-$(date +'%Y%m%d%H%M%S')"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Rename signed APK
        run: |
          mkdir -p renamed
          cp app/build/outputs/apk/release/app-release.apk renamed/curtain-app.${{ env.VERSION }}.signed.apk
          echo "RENAMED_APK=renamed/curtain-app.${{ env.VERSION }}.signed.apk" >> $GITHUB_ENV

      - name: Rename signed Bundle
        run: |
          cp app/build/outputs/bundle/release/app-release.aab renamed/curtain-app.${{ env.VERSION }}.signed.aab
          echo "RENAMED_BUNDLE=renamed/curtain-app.${{ env.VERSION }}.signed.aab" >> $GITHUB_ENV

      - name: Upload Curtain App APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: curtain-app-apk
          path: ${{ env.RENAMED_APK }}

      - name: Upload Curtain App Bundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: curtain-app-bundle
          path: ${{ env.RENAMED_BUNDLE }}

  # Release job
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-curtain-app]
    if: needs.build-curtain-app.result == 'success' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download Curtain App APK
        uses: actions/download-artifact@v4
        with:
          name: curtain-app-apk
          path: ./artifacts/

      - name: Download Curtain App Bundle
        uses: actions/download-artifact@v4
        with:
          name: curtain-app-bundle
          path: ./artifacts/

      - name: List artifacts
        run: ls -la ./artifacts/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/*
          body: |
            ## Curtain Android Release
            
            This release includes:
            - 📱 Curtain Android app
            - 📦 Android App Bundle (AAB) for Play Store
            
            ### Installation
            - Install `curtain-app.*.apk` on your Android device
            - Use `curtain-app.*.aab` for Play Store publishing
            
            ### Features
            - Built with Android 35 (API level 35)
            - Minimum Android 8.0 (API level 26)
            - Includes Plotly.js and QR Code Styling assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
