name: Build Android APK

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Download Plotly.js
      run: ./gradlew downloadPlotly

    - name: Download QR Code Styling
      run: ./gradlew downloadQRCodeStyling

    - name: Build debug APK
      run: ./gradlew assembleDebug

    - name: Build release APK (unsigned)
      run: ./gradlew assembleRelease

    - name: Sign release APK
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > curtain-release-key.keystore
        $ANDROID_HOME/build-tools/*/apksigner sign \
          --ks curtain-release-key.keystore \
          --ks-key-alias curtain-key \
          --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
          --key-pass pass:${{ secrets.KEY_PASSWORD }} \
          --out app/build/outputs/apk/release/app-release-signed.apk \
          app/build/outputs/apk/release/app-release-unsigned.apk

    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: curtain-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Upload release APK (unsigned)
      if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: curtain-release-unsigned-apk
        path: app/build/outputs/apk/release/app-release-unsigned.apk

    - name: Upload signed release APK
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: curtain-release-signed-apk
        path: app/build/outputs/apk/release/app-release-signed.apk

    - name: Run tests
      run: ./gradlew test

    - name: Run lint
      run: ./gradlew lint

    - name: Upload lint results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lint-results
        path: app/build/reports/lint-results-debug.html